apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-binding
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers # Required.
    value: "localhost:9092"
  - name: consumerGroup # Optional. Used for input bindings.
    value: "refractory"
  - name: publishTopic # Optional. Used for output bindings.
    value: "fplims"
  - name: authRequired # Required.
    value: "false"
  - name: initialOffset # Optional. Used for input bindings.
    value: "newest"
  - name: maxMessageBytes # Optional.
    value: 1024
  - name: version # Optional.
    value: 1.0.0