name: CI for PRs to develop and master

on:
  pull_request:
    branches: [develop, main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:


    - uses: toko-bifrost/ms-teams-deploy-card@master
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_BUILD_STATUS }}

    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGES_PAT: ${{ secrets.PACKAGES_PAT }}
        GITHUB_USER: orion6dev
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/lungmuss/index.json -n github -u $GITHUB_USER -p $PACKAGES_PAT --store-password-in-clear-text
        dotnet restore

    - name: Build with Code Style Checking
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal